apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infinite-buying
resources:
  - ../../base
patches:
  - path: patches/ingress-tls.yaml
    target:
      kind: Ingress
      name: infinite-buying
  - path: patches/ingress-www-tls.yaml
    target:
      kind: Ingress
      name: infinite-buying-www
images:
  - name: infinite-buying-backend
    newName: yny.ocir.io/axnyuujz40an/infinite-buying-backend
    newTag: 59b61aa1a4121cf5cf841ebbc4a8d53fd586a79e
  - name: infinite-buying-frontend
    newName: yny.ocir.io/axnyuujz40an/infinite-buying-frontend
    newTag: 59b61aa1a4121cf5cf841ebbc4a8d53fd586a79e
