apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infinite-buying
resources:
  - ../../base
patches:
  - path: patches/ingress-tls.yaml
    target:
      kind: Ingress
      name: infinite-buying
  - path: patches/ingress-www-tls.yaml
    target:
      kind: Ingress
      name: infinite-buying-www
images:
  - name: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/infinite-buying-backend
    newName: 107015853205.dkr.ecr.ap-northeast-2.amazonaws.com/infinite-buying-backend
    newTag: b6811d0a5838d57f11ea86e36231083aa4001be3
  - name: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/infinite-buying-frontend
    newName: 107015853205.dkr.ecr.ap-northeast-2.amazonaws.com/infinite-buying-frontend
    newTag: b6811d0a5838d57f11ea86e36231083aa4001be3
