apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-refresher
  namespace: infinite-buying
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-refresher
  namespace: infinite-buying
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-refresher
  namespace: infinite-buying
subjects:
  - kind: ServiceAccount
    name: ecr-refresher
    namespace: infinite-buying
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-refresher
