apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infinite-buying-www
  namespace: infinite-buying
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - www.DOMAIN_PLACEHOLDER
      secretName: infinite-buying-tls-secret
  rules:
    - host: www.DOMAIN_PLACEHOLDER
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: infinite-buying-frontend
                port:
                  number: 80
