apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: infinite-buying-www-redirect
  namespace: infinite-buying
spec:
  redirectRegex:
    regex: ^https://www\.infinite-buying\.yuna-pa\.com/(.*)
    replacement: https://infinite-buying.yuna-pa.com/${1}
    permanent: true
